version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
  db:
    image: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
